### ISSUE TITLE
Стили таблиц

### ISSUE THREAD

**Issue by amargoev** [magr0s/bspa#1]
Сделать стили таблиц для прайсов.

**Comment by magr0s** [comment]
Done.

<table class="pricetable">

	<thead>
		<tr>
			<th class="pricetable-name" colspan="2"></th>
		</tr>
	</thead>

	<tbody>
	
		<tr>
			<th class="service-title" colspan="2"></th>
		</tr>
		<tr>
			<th class="cost-desc" colspan="2"></th>
		</tr>
	
	
		<tr>
			<td></td>
			<td></td>
		</tr>
		
	</tbody>
</table>
