### ISSUE TITLE
SPA-программы на страницах услуг

### ISSUE THREAD

**Issue by amargoev** [magr0s/bspa#2]
"выяснил ситуацию у программиста. В итоге получается, что SPA-программы нужно отдельно заводить для каждой страницы."
Вопрос:
Шаблон для этих страниц надо менять? В этом шаблоне я не вижу возможности добавлять программы?

**Comment by magr0s** [comment]
для вопросов скайп magr0s здесь только баг фиксы
шаблон programms.tpl
